config/routes.rb
Rails.application.routes.draw do



  resources :projects

  resources :mfarmkzizs do
  	collection {post :import}
  end

  resources :entypos do
  	collection {post :import}
  end

  resources :mfarmakos do
  	collection {post :import}
  end

#============Chem resources ======
  #=====Imported CSVs======

  resources :mastfarms do
  	collection {post :import}
  end

  resources :mfarmkasts do
  	collection {post :import}
  end

  resources :mcfarmasts do 
  	collection {post :import}
  end

  resources :mdoshes do
  	collection {post :import}
  end

  resources :masthenia do
  	collection {post :import}
  end

  resources :mkatigoris do
  	collection {post :import}
  end

  resources :mfcs do
	  collection {post :import}
  end

  resources :farm_dros do
	  collection{post :import}
  end

  
#4.Systatik imports all the prime ingredients 
  resources :systatiks,param: :kodikos  do
	  collection {post :import}
  end

  
#3.Mepembash imports  the phi (diast_pros) is a join table (mcrop and farmako)
  resources :mepembashes do
	  collection {post :import}
  end

#2. Farmakos imports all chems for brand name 
  resources :farmakos ,param: :kod_farmak do
	  collection {post :import}
  end

#1.Mcrops imports all the crops 
# the get mcrops/produce_20 is  a scope to list selected crops 
  get 'mcrops/produce_20'=>'mcrops#index',scpope: 'produce_10'
  resources :mcrops ,param: :code_fyta do
	  collection {post :import}
  end
#========End of Chems =======================
	root "groups#index"

	namespace :team do
	resources :registrations
	end

	resources :groups do
	  namespace :team do
		 resources :registrations
	  end
	end

	namespace :team do
	  resources :registrations,:only=>[:show] do
			resources :pmus
		end
	end
  resources :growers,:produces,:standards

  resources :pmus do
		resources :productions
	end


	namespace :team do
		resources :registrations,:only=>[:show] do

			resources :activities
			resources :fertilizations,controller:'activities',type:'Fertilization'
			resources :irrigations, controller: 'activities',type:'Irrigation'
			resources :protections, controller: 'activities',type:'Protection'
			resources :cultivations, controller:'activities',type:'Cultivation'
			resources :harvestings,controller: 'activities',type:'Harvesting'

			get 'activities/fertilizations'=>"activities#index",scope:'fertilizations'
			# get 'activities/irrigations'=>"activities#index",scope:'irrigations'
			# get 'activities/protections'=>"activities#index",scope:'protections'


		end

	end


	resources :activities do
		resources :chems
	end
	resources :fertilizations,controller:'activities',type:'Fertilization'
	resources :irrigations, controller: 'activities',type:'Irrigation'
	resources :protections, controller: 'activities',type:'Protection'
	resources :cultivations, controller:'activities',type:'Cultivation'
	resources :harvestings,  controller:'activities',type:'Harvesting'








	get 'pages/about'
  	get 'pages/contact'
  	get 'pages/chems'

	devise_for :users








end

app/models/group.rb
class Group < ActiveRecord::Base

	has_many :registrations,dependent: :destroy
	has_many :pmus, through: :registrations
	has_many :productions,through: :pmus



	#has_many :memberships ,dependent: :destroy
	#has_many :growers,through: :memberships
	has_many :produces,through: :productions
	has_many :certifications,through: :productions
	has_many :standards,through: :certifications

	belongs_to :user

	mount_uploader :avatar, AvatarUploader

	def team_registrations
		# code here
	end

	def team_registrations
		# code here
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_filter:authenticate_user!
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where(user:current_user)
    # @groups=Group.all
		respond_to do |format|
			format.html
			format.pdf do
				pdf = GroupsPdf.new(@groups)
				send_data pdf.render,filename:'groups.pdf',
						type:'application/pdf',
						disposition:"inline"
			end
		end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
		@group=Group.find(params[:id])
		@registrations=@group.registrations
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id=current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :address, :phone, :email,:avatar,:remove_avatar,:user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group,:html=>{multipart: true}) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name,class:'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address,class:'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone ,class:'form-control'%>
  </div>
    <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email,class:'form-control' %>
  </div>

    <div class="form-group">
      <%= f.label :avatar %><br>
      <%= image_tag(@group.avatar_url(:thumb)) if @group.avatar?%>
      <%= f.file_field :avatar,class:'form-control' %>
      <%=f.hidden_field :avatar_cache %>
      <%= f.label :Remove_avatar %>
      <%= f.check_box :remove_avatar %>
    </div>


  <div class="actions">
    <%= f.submit class:'btn btn-default'%>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @group ,class:'btn btn-link' %> |
<%= link_to 'Delete', @group,method: :delete,class:'btn btn-link'  %>

app/views/groups/index.html.erb
<h3>
<%=link_to "+ Start a new Group",new_group_path%></h3>
<br>


<!-- <div class='container'> -->
  <div class='row'>
  <div class='col-md-6'>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th class='col-md-1'></th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr data-link="<%=group_path(group)%>">
        <td><%= image_tag group.avatar_url(:thumb),class:'img-rounded'if group.avatar? %></td>
        <td><%= group.name %></td>
        <td><%= group.address %></td>
        <td><%= group.phone %></td>
        <td><%= group.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%=image_tag "https://s3.amazonaws.com/instagap/happy_footer.png"  ,class:'img-responsive'%>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path,class:'btn btn-link'  %>

app/views/groups/show.html.erb
<%=link_to "<<=Back to your projects(Groups/index)", groups_path ,class:'btn btn-link'%>
 <div class="jumbotron">
  <div class="row">
    <div class="col-xs-3 col-xs-offset">
    <h2></h2>
    <%=image_tag @group.avatar_url(:mid) ,class:'img-responsive img-rounded' if @group.avatar %>

  </div>
  <div class="col-xs-9">
    <h2><%= @group.name %><br/>
    <small><%= @group.address %><br/>
    <%= @group.phone %>
    <%= @group.email %></small></h2>

    <%= link_to 'Edit', edit_group_path(@group) ,class:'btn btn-link' %>
  </div>
 </div>
   </div>
<p>
<% content_for (:side) do %>
 <% if @group.registrations.any? %>
  <div >
    <h4 class='text-center'><%=@group.name%> <span>Tel:<%=@group.phone%></h4>
    <p>
      <%=link_to " + Νέο Μέλος!",new_group_team_registration_path(@group),class:'btn btn-default btn-sm center-block'%>
    </p>
    

    <% @group.registrations.each do |r|%>
    <ul>
      <li> <%=link_to "#{r.name} -#{r.role}",group_team_registration_path(@group,r)%></li>
    </ul>
    <%end%>
  </div>
<%end%>
</p>
<%end%>


<p>
  <%=link_to "+ Νέο Μέλος!",new_group_team_registration_path(@group),class:'btn btn-link'%>
</p>
<hr>