config/routes.rb
Rails.application.routes.draw do



  resources :projects

  resources :mfarmkzizs do
  	collection {post :import}
  end

  resources :entypos do
  	collection {post :import}
  end

  resources :mfarmakos do
  	collection {post :import}
  end

#============Chem resources ======
  #=====Imported CSVs======

  resources :mastfarms do
  	collection {post :import}
  end

  resources :mfarmkasts do
  	collection {post :import}
  end

  resources :mcfarmasts do 
  	collection {post :import}
  end

  resources :mdoshes do
  	collection {post :import}
  end

  resources :masthenia do
  	collection {post :import}
  end

  resources :mkatigoris do
  	collection {post :import}
  end

  resources :mfcs do
	  collection {post :import}
  end

  resources :farm_dros do
	  collection{post :import}
  end

  
#4.Systatik imports all the prime ingredients 
  resources :systatiks,param: :kodikos  do
	  collection {post :import}
  end

  
#3.Mepembash imports  the phi (diast_pros) is a join table (mcrop and farmako)
  resources :mepembashes do
	  collection {post :import}
  end

#2. Farmakos imports all chems for brand name 
  resources :farmakos ,param: :kod_farmak do
	  collection {post :import}
  end

#1.Mcrops imports all the crops 
# the get mcrops/produce_20 is  a scope to list selected crops 
  get 'mcrops/produce_20'=>'mcrops#index',scpope: 'produce_10'
  resources :mcrops ,param: :code_fyta do
	  collection {post :import}
  end
#========End of Chems =======================
	root "groups#index"

	namespace :team do
	resources :registrations
	end

	resources :groups do
	  namespace :team do
		 resources :registrations
	  end
	end

	namespace :team do
	  resources :registrations,:only=>[:show] do
			resources :pmus
		end
	end
  resources :growers,:produces,:standards

  resources :pmus do
		resources :productions
	end


	namespace :team do
		resources :registrations,:only=>[:show] do

			resources :activities
			resources :fertilizations,controller:'activities',type:'Fertilization'
			resources :irrigations, controller: 'activities',type:'Irrigation'
			resources :protections, controller: 'activities',type:'Protection'
			resources :cultivations, controller:'activities',type:'Cultivation'
			resources :harvestings,controller: 'activities',type:'Harvesting'

			get 'activities/fertilizations'=>"activities#index",scope:'fertilizations'
			# get 'activities/irrigations'=>"activities#index",scope:'irrigations'
			# get 'activities/protections'=>"activities#index",scope:'protections'


		end

	end


	resources :activities do
		resources :chems
	end
	resources :fertilizations,controller:'activities',type:'Fertilization'
	resources :irrigations, controller: 'activities',type:'Irrigation'
	resources :protections, controller: 'activities',type:'Protection'
	resources :cultivations, controller:'activities',type:'Cultivation'
	resources :harvestings,  controller:'activities',type:'Harvesting'








	get 'pages/about'
  	get 'pages/contact'
  	get 'pages/chems'

	devise_for :users








end

app/models/systatik.rb
class Systatik < ActiveRecord::Base
#Chem associations and primary keys
	self.primary_key="kodikos"
	has_many :farm_dros
	has_many :mfarmakos,through: :farm_dros



  def self.import(file)

  	CSV.foreach(file.path ,headers: true,:header_converters =>lambda{|h| h.downcase.gsub('-','_').gsub(' ','_')}) do |row|

  		systatik_hash=row.to_hash
  		systatik=Systatik.where(kodikos: systatik_hash["kodikos"])
  		if systatik==1
  			systatik.first.update_attributes(systatik_hash)
  		else
  			Systatik.create!(systatik_hash)
  		end
  	end
  end


end

app/controllers/systatiks_controller.rb
class SystatiksController < ApplicationController
  before_action :set_systatik, only: [:show, :edit, :update, :destroy]
  before_filter :authebticate_user!

  respond_to :html

  def index
    @systatiks = Systatik.all
    respond_with(@systatiks)
  end

  def import
	  Systatik.import(params[:file])
		redirect_to systatiks_url,notice: "Systatiks impoted successfully !"
  end

  def show
    respond_with(@systatik)
  end

  def new
    @systatik = Systatik.new
    respond_with(@systatik)
  end

  def edit
  end

  def create
    @systatik = Systatik.new(systatik_params)
    @systatik.save
    respond_with(@systatik)
  end

  def update
    @systatik.update(systatik_params)
    respond_with(@systatik)
  end

  def destroy
    @systatik.destroy
    respond_with(@systatik)
  end

  private
    def set_systatik
      @systatik = Systatik.find(params[:kodikos])
    end

    def systatik_params
      params.require(:systatik).permit(:kodikos, :omadron, :arxiko, :aposyrsh, :cipac, :dr_cod_kat, :old_new, :fao, :cas_number, :code_xhmik)
    end
end

app/helpers/systatiks_helper.rb
module SystatiksHelper
end

app/views/systatiks/_form.html.erb
<%= form_for(@systatik) do |f| %>
  <% if @systatik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@systatik.errors.count, "error") %> prohibited this systatik from being saved:</h2>

      <ul>
      <% @systatik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kodikos %><br>
    <%= f.text_field :kodikos %>
  </div>
  <div class="field">
    <%= f.label :omadron %><br>
    <%= f.text_field :omadron %>
  </div>
  <div class="field">
    <%= f.label :arxiko %><br>
    <%= f.text_field :arxiko %>
  </div>
  <div class="field">
    <%= f.label :aposyrsh %><br>
    <%= f.text_field :aposyrsh %>
  </div>
  <div class="field">
    <%= f.label :cipac %><br>
    <%= f.number_field :cipac %>
  </div>
  <div class="field">
    <%= f.label :dr_cod_kat %><br>
    <%= f.text_field :dr_cod_kat %>
  </div>
  <div class="field">
    <%= f.label :old_new %><br>
    <%= f.text_field :old_new %>
  </div>
  <div class="field">
    <%= f.label :fao %><br>
    <%= f.text_field :fao %>
  </div>
  <div class="field">
    <%= f.label :cas_number %><br>
    <%= f.text_field :cas_number %>
  </div>
  <div class="field">
    <%= f.label :code_xhmik %><br>
    <%= f.number_field :code_xhmik %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/systatiks/edit.html.erb
<h1>Editing Systatik</h1>

<%= render 'form' %>

<%= link_to 'Show', @systatik %> |
<%= link_to 'Back', systatiks_path %>

app/views/systatiks/index.html.erb
<h3>Import Systatiks</h3>
<%=form_tag import_systatiks_path,multipart:true do %>
    <%=file_field_tag :file%>
    <%=submit_tag "Import csv"%>
<%end%>

<br>
<%= link_to 'New Systatik', new_systatik_path %>


<h1>Listing Systatiks</h1>

<table class="'table">
  <thead>
    <tr>
      <th>Kodikos</th>
      <th>Onomadron</th>
      <th>Arxiko</th>
      <th>Aposyrsh</th>
      <th>Cipac</th>
      <th>Dr cod kat</th>
      <th>Old new</th>
      <th>Fao</th>
      <th>Cas number</th>
      <th>Code xhmik</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @systatiks.each do |systatik| %>
      <tr>
        <td><%= systatik.kodikos %></td>
        <td><%= systatik.onomadron %></td>
        <td><%= systatik.arxiko %></td>
        <td><%= systatik.aposyrsh %></td>
        <td><%= systatik.cipac %></td>
        <td><%= systatik.dr_cod_kat %></td>
        <td><%= systatik.old_new %></td>
        <td><%= systatik.fao %></td>
        <td><%= systatik.cas_number %></td>
        <td><%= systatik.code_xhmik %></td>
        <td><%= link_to 'Show', systatik %></td>
        <td><%= link_to 'Edit', edit_systatik_path(systatik) %></td>
        <td><%= link_to 'Destroy', systatik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/systatiks/new.html.erb
<h1>New Systatik</h1>

<%= render 'form' %>

<%= link_to 'Back', systatiks_path %>

app/views/systatiks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kodikos:</strong>
  <%= @systatik.kodikos %>
</p>

<p>
  <strong>Omadron:</strong>
  <%= @systatik.omadron %>
</p>

<p>
  <strong>Arxiko:</strong>
  <%= @systatik.arxiko %>
</p>

<p>
  <strong>Aposyrsh:</strong>
  <%= @systatik.aposyrsh %>
</p>

<p>
  <strong>Cipac:</strong>
  <%= @systatik.cipac %>
</p>

<p>
  <strong>Dr cod kat:</strong>
  <%= @systatik.dr_cod_kat %>
</p>

<p>
  <strong>Old new:</strong>
  <%= @systatik.old_new %>
</p>

<p>
  <strong>Fao:</strong>
  <%= @systatik.fao %>
</p>

<p>
  <strong>Cas number:</strong>
  <%= @systatik.cas_number %>
</p>

<p>
  <strong>Code xhmik:</strong>
  <%= @systatik.code_xhmik %>
</p>

<%= link_to 'Edit', edit_systatik_path(@systatik) %> |
<%= link_to 'Back', systatiks_path %>