config/routes.rb
Rails.application.routes.draw do



  resources :projects

  resources :mfarmkzizs do
  	collection {post :import}
  end

  resources :entypos do
  	collection {post :import}
  end

  resources :mfarmakos do
  	collection {post :import}
  end

#============Chem resources ======
  #=====Imported CSVs======

  resources :mastfarms do
  	collection {post :import}
  end

  resources :mfarmkasts do
  	collection {post :import}
  end

  resources :mcfarmasts do 
  	collection {post :import}
  end

  resources :mdoshes do
  	collection {post :import}
  end

  resources :masthenia do
  	collection {post :import}
  end

  resources :mkatigoris do
  	collection {post :import}
  end

  resources :mfcs do
	  collection {post :import}
  end

  resources :farm_dros do
	  collection{post :import}
  end

  
#4.Systatik imports all the prime ingredients 
  resources :systatiks,param: :kodikos  do
	  collection {post :import}
  end

  
#3.Mepembash imports  the phi (diast_pros) is a join table (mcrop and farmako)
  resources :mepembashes do
	  collection {post :import}
  end

#2. Farmakos imports all chems for brand name 
  resources :farmakos ,param: :kod_farmak do
	  collection {post :import}
  end

#1.Mcrops imports all the crops 
# the get mcrops/produce_20 is  a scope to list selected crops 
  get 'mcrops/produce_20'=>'mcrops#index',scpope: 'produce_10'
  resources :mcrops ,param: :code_fyta do
	  collection {post :import}
  end
#========End of Chems =======================
	root "groups#index"

	namespace :team do
	resources :registrations
	end

	resources :groups do
	  namespace :team do
		 resources :registrations
	  end
	end

	namespace :team do
	  resources :registrations,:only=>[:show] do
			resources :pmus
		end
	end
  resources :growers,:produces,:standards

  resources :pmus do
		resources :productions
	end


	namespace :team do
		resources :registrations,:only=>[:show] do

			resources :activities
			resources :fertilizations,controller:'activities',type:'Fertilization'
			resources :irrigations, controller: 'activities',type:'Irrigation'
			resources :protections, controller: 'activities',type:'Protection'
			resources :cultivations, controller:'activities',type:'Cultivation'
			resources :harvestings,controller: 'activities',type:'Harvesting'

			get 'activities/fertilizations'=>"activities#index",scope:'fertilizations'
			# get 'activities/irrigations'=>"activities#index",scope:'irrigations'
			# get 'activities/protections'=>"activities#index",scope:'protections'


		end

	end


	resources :activities do
		resources :chems
	end
	resources :fertilizations,controller:'activities',type:'Fertilization'
	resources :irrigations, controller: 'activities',type:'Irrigation'
	resources :protections, controller: 'activities',type:'Protection'
	resources :cultivations, controller:'activities',type:'Cultivation'
	resources :harvestings,  controller:'activities',type:'Harvesting'








	get 'pages/about'
  	get 'pages/contact'
  	get 'pages/chems'

	devise_for :users








end

app/models/mastfarm.rb
class Mastfarm < ActiveRecord::Base
# belongs_to :entypo
belongs_to :mdosh
belongs_to :masthenium
belongs_to :mfarmkast

 
	def self.import(file)
		CSV.foreach(file.path,headers:true,:header_converters=>lambda{|h| h.try(:downcase).gsub('-','_').gsub(' ','_').gsub('counter','counterable_id').gsub('code_asten','masthenium_id').gsub('kod_doshs','mdosh_id')}) do |row|
			mastfarm_hash=row.to_hash
			mastfarm=Mastfarm.where(counter: mastfarm_hash['counter'])
			if mastfarm==1
				mastfarm.first.update_attributes(mastfarm_hash)
			else
				Mastfarm.create!(mastfarm_hash)
			end
	   end
	end
end

app/controllers/mastfarms_controller.rb
class MastfarmsController < ApplicationController
  before_action :set_mastfarm, only: [:show, :edit, :update, :destroy]

  # GET /mastfarms
  # GET /mastfarms.json
  def index
    @mastfarms = Mastfarm.limit(100)
  end

  def import
    Mastfarm.import(params[:file])
    redirect_to mastfarms_url,notice:"Mastfarms successfully imported!"
  end

  # GET /mastfarms/1
  # GET /mastfarms/1.json
  def show
  end

  # GET /mastfarms/new
  def new
    @mastfarm = Mastfarm.new
  end

  # GET /mastfarms/1/edit
  def edit
  end

  # POST /mastfarms
  # POST /mastfarms.json
  def create
    @mastfarm = Mastfarm.new(mastfarm_params)

    respond_to do |format|
      if @mastfarm.save
        format.html { redirect_to @mastfarm, notice: 'Mastfarm was successfully created.' }
        format.json { render :show, status: :created, location: @mastfarm }
      else
        format.html { render :new }
        format.json { render json: @mastfarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mastfarms/1
  # PATCH/PUT /mastfarms/1.json
  def update
    respond_to do |format|
      if @mastfarm.update(mastfarm_params)
        format.html { redirect_to @mastfarm, notice: 'Mastfarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @mastfarm }
      else
        format.html { render :edit }
        format.json { render json: @mastfarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mastfarms/1
  # DELETE /mastfarms/1.json
  def destroy
    @mastfarm.destroy
    respond_to do |format|
      format.html { redirect_to mastfarms_url, notice: 'Mastfarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mastfarm
      @mastfarm = Mastfarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mastfarm_params
      params.require(:mastfarm).permit(:counter, :code_asten, :fbcode, :dosh_farm, :kod_doshs,:counterable_type)
    end
end

app/helpers/mastfarms_helper.rb
module MastfarmsHelper
end

app/views/mastfarms/_form.html.haml
= form_for @mastfarm do |f|
  - if @mastfarm.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mastfarm.errors.count, "error")} prohibited this mastfarm from being saved:"
      %ul
        - @mastfarm.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :counterable_id
    = f.number_field :counterable_id
  .field
    = f.label :masthenium_id
    = f.text_field :masthenium_id
  .field
    = f.label :fbcode
    = f.text_field :fbcode
  .field
    = f.label :dosh_farm
    = f.text_field :dosh_farm
  .field
    = f.label :mdosh_id
    = f.number_field :mdosh_id
  .actions
    = f.submit 'Save'

app/views/mastfarms/edit.html.haml
%h1 Editing mastfarm

= render 'form'

= link_to 'Show', @mastfarm
\|
= link_to 'Back', mastfarms_path

app/views/mastfarms/index.html.haml
%h1 Listing mastfarms
%p
  =form_tag import_mastfarms_path,multipart:true do
    =file_field_tag :file,class:'btn'
    =submit_tag "Import CSV",class:'btn btn-link'
%p
  = link_to 'New Mastfarm', new_mastfarm_path,class:'btn btn-link'


%table
  %thead
    %tr
      %th Counter
      %th Code asten
      %th Fbcode
      %th Dosh farm
      %th Kod doshs
      %th
      %th
      %th

  %tbody
    - @mastfarms.each do |mastfarm|
      %tr
        %td= mastfarm.counterable_id
        %td= mastfarm.masthenium_id
        %td= mastfarm.fbcode
        %td= mastfarm.dosh_farm
        %td= mastfarm.mdosh_id
        %td= link_to 'Show', mastfarm
        %td= link_to 'Edit', edit_mastfarm_path(mastfarm)
        %td= link_to 'Destroy', mastfarm, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/mastfarms/new.html.haml
%h1 New mastfarm

= render 'form'

= link_to 'Back', mastfarms_path

app/views/mastfarms/show.html.haml
%p#notice= notice

%p
  %b Counter:
  = @mastfarm.counter
%p
  %b Code asten:
  = @mastfarm.code_asten
%p
  %b Fbcode:
  = @mastfarm.fbcode
%p
  %b Dosh farm:
  = @mastfarm.dosh_farm
%p
  %b Kod doshs:
  = @mastfarm.kod_doshs

= link_to 'Edit', edit_mastfarm_path(@mastfarm)
\|
= link_to 'Back', mastfarms_path