config/routes.rb
Rails.application.routes.draw do



  resources :projects

  resources :mfarmkzizs do
  	collection {post :import}
  end

  resources :entypos do
  	collection {post :import}
  end

  resources :mfarmakos do
  	collection {post :import}
  end

#============Chem resources ======
  #=====Imported CSVs======

  resources :mastfarms do
  	collection {post :import}
  end

  resources :mfarmkasts do
  	collection {post :import}
  end

  resources :mcfarmasts do 
  	collection {post :import}
  end

  resources :mdoshes do
  	collection {post :import}
  end

  resources :masthenia do
  	collection {post :import}
  end

  resources :mkatigoris do
  	collection {post :import}
  end

  resources :mfcs do
	  collection {post :import}
  end

  resources :farm_dros do
	  collection{post :import}
  end

  
#4.Systatik imports all the prime ingredients 
  resources :systatiks,param: :kodikos  do
	  collection {post :import}
  end

  
#3.Mepembash imports  the phi (diast_pros) is a join table (mcrop and farmako)
  resources :mepembashes do
	  collection {post :import}
  end

#2. Farmakos imports all chems for brand name 
  resources :farmakos ,param: :kod_farmak do
	  collection {post :import}
  end

#1.Mcrops imports all the crops 
# the get mcrops/produce_20 is  a scope to list selected crops 
  get 'mcrops/produce_20'=>'mcrops#index',scpope: 'produce_10'
  resources :mcrops ,param: :code_fyta do
	  collection {post :import}
  end
#========End of Chems =======================
	root "groups#index"

	namespace :team do
	resources :registrations
	end

	resources :groups do
	  namespace :team do
		 resources :registrations
	  end
	end

	namespace :team do
	  resources :registrations,:only=>[:show] do
			resources :pmus
		end
	end
  resources :growers,:produces,:standards

  resources :pmus do
		resources :productions
	end


	namespace :team do
		resources :registrations,:only=>[:show] do

			resources :activities
			resources :fertilizations,controller:'activities',type:'Fertilization'
			resources :irrigations, controller: 'activities',type:'Irrigation'
			resources :protections, controller: 'activities',type:'Protection'
			resources :cultivations, controller:'activities',type:'Cultivation'
			resources :harvestings,controller: 'activities',type:'Harvesting'

			get 'activities/fertilizations'=>"activities#index",scope:'fertilizations'
			# get 'activities/irrigations'=>"activities#index",scope:'irrigations'
			# get 'activities/protections'=>"activities#index",scope:'protections'


		end

	end


	resources :activities do
		resources :chems
	end
	resources :fertilizations,controller:'activities',type:'Fertilization'
	resources :irrigations, controller: 'activities',type:'Irrigation'
	resources :protections, controller: 'activities',type:'Protection'
	resources :cultivations, controller:'activities',type:'Cultivation'
	resources :harvestings,  controller:'activities',type:'Harvesting'








	get 'pages/about'
  	get 'pages/contact'
  	get 'pages/chems'

	devise_for :users








end

app/models/produce.rb
class Produce < ActiveRecord::Base
	has_many :productions
	has_many :pmus,through: :productions
	has_many :growers,through: :pmus
	has_many :groups,through: :growers
	has_many :certifications,through: :productions
	has_many :standards,through: :certifications
end

app/controllers/produces_controller.rb
class ProducesController < ApplicationController
  before_action :set_produce, only: [:show, :edit, :update, :destroy]

  # GET /produces
  # GET /produces.json
  def index
    # @produces = Produce.all
    @produces=Mcrop.where(code_fyta:1140000..1140900)
  end

  # GET /produces/1
  # GET /produces/1.json
  def show
  end

  # GET /produces/new
  def new
    @produce = Produce.new
  end

  # GET /produces/1/edit
  def edit
  end

  # POST /produces
  # POST /produces.json
  def create
    @produce = Produce.new(produce_params)

    respond_to do |format|
      if @produce.save
        format.html { redirect_to @produce, notice: 'Produce was successfully created.' }
        format.json { render :show, status: :created, location: @produce }
      else
        format.html { render :new }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produces/1
  # PATCH/PUT /produces/1.json
  def update
    respond_to do |format|
      if @produce.update(produce_params)
        format.html { redirect_to @produce, notice: 'Produce was successfully updated.' }
        format.json { render :show, status: :ok, location: @produce }
      else
        format.html { render :edit }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produces/1
  # DELETE /produces/1.json
  def destroy
    @produce.destroy
    respond_to do |format|
      format.html { redirect_to produces_url, notice: 'Produce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produce
      @produce = Produce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produce_params
      params.require(:produce).permit(:name)
    end
end

app/helpers/produces_helper.rb
module ProducesHelper
end

app/views/produces/_form.html.erb
<%= form_for(@produce) do |f| %>
  <% if @produce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produce.errors.count, "error") %> prohibited this produce from being saved:</h2>

      <ul>
      <% @produce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name,class:'form-control'  %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-default' %>
  </div>
<% end %>

app/views/produces/edit.html.erb
<h1>Editing Produce</h1>

<%= render 'form' %>

<%= link_to 'Show', @produce,class:'btn btn-link'  %> |
<%= link_to 'Back', produces_path,class:'btn btn-link'  %>

app/views/produces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Produces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produces.each do |produce| %>
      <tr>
        <td><%= produce.gonoma %></td>
        <td><%= link_to 'Show', produce,class:'btn btn-link'  %></td>
        <td><%= link_to 'Edit', edit_produce_path(produce) ,class:'btn btn-link' %></td>
        <td><%= link_to 'Destroy', produce, method: :delete, data: { confirm: 'Are you sure?' } ,class:'btn btn-link' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produce', new_produce_path,class:'btn btn-link'  %>

app/views/produces/new.html.erb
<h1>New Produce</h1>

<%= render 'form' %>

<%= link_to 'Back', produces_path,class:'btn btn-link'  %>

app/views/produces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @produce.name %>
</p>

<%= link_to 'Edit', edit_produce_path(@produce) ,class:'btn btn-link' %> |
<%= link_to 'Back', produces_path,class:'btn btn-link'  %>